"""Public analysis API for physiology-token experiments.

The ``physiological_patch_features``, ``token_physiology`` and
``token_sequence`` modules form the standard Token Physiology Atlas surface.
Helpers imported from ``coupling_identifiability`` remain available for exact
replay of historical experiment suites.
"""

from .coupling_identifiability import (
    build_lag_pair_table,
    conditional_probabilities_from_counts,
    effective_conditional_probabilities,
    gaussian_conditional_mutual_information,
    lag_mutual_information,
    load_export_split,
    loso_ridge_scores,
    occupancy_weighted_gauge,
    patch_features,
    patch_features_torch,
    subject_block_bootstrap_gain,
)
from .physiological_patch_features import (
    CANONICAL_SIGNAL_UNIT,
    DEFAULT_FEATURE_SPEC,
    FEATURE_SPEC_SCHEMA_VERSION,
    FeatureDefinition,
    FeatureExtractionManifest,
    FrequencyBand,
    PatchFeatureBatch,
    PhysiologicalPatchFeatureSpec,
    extract_eeg_patch_features,
    extract_fnirs_patch_features,
    extract_physiological_patch_features,
)
from .token_physiology import (
    TOKEN_PHYSIOLOGY_SCHEMA_VERSION,
    TokenPhysiologyConfig,
    TokenPhysiologyResult,
    analyze_token_physiology,
    match_token_signatures,
)
from .token_information_ledger import (
    InformationLedgerConfig,
    TOKEN_INFORMATION_LEDGER_SCHEMA_VERSION,
    build_token_representations,
    evaluate_information_ledger,
)
from .token_physiology_atlas import (
    ATLAS_SCHEMA_VERSION,
    ModalitySplitAtlas,
    analyze_export_split,
    build_token_physiology_atlas,
    load_token_export,
    prepare_measurement_feature_caches,
)
from .token_sequence import (
    SEQUENCE_ANALYSIS_SCHEMA,
    SequenceSummary,
    analyze_cross_modal_lags,
    circular_shift_coupling_null,
    coupling_metrics_from_counts,
    cross_modal_lag_counts,
    markov_log_loss,
    occupancy_counts,
    summarize_sequences,
    transition_counts,
)
from .lag_conditioned_native_features import (
    EEG_NATIVE_FEATURES,
    FNIRS_COMPONENT_ROLES,
    FNIRS_NATIVE_FEATURES,
    MaskedStandardizer,
    NativeFeatureTargets,
    apply_masked_standardizer,
    extract_eeg_native_targets,
    extract_fnirs_native_targets,
    fit_masked_standardizer,
)
from .lagged_token_coupling import (
    CategoricalModel,
    LAGGED_COUPLING_SCHEMA_VERSION,
    LaggedCategoricalRows,
    Q0Q1Models,
    TokenOrder,
    apply_token_order,
    build_lagged_categorical_rows,
    categorical_proper_scores,
    conditional_fnirs_given_eeg,
    conditional_log_lift,
    dirichlet_conditional,
    dirichlet_smoothed_conditional,
    evaluate_categorical_model,
    evaluate_categorical_proper_score_increment,
    evaluate_q0_q1,
    evaluate_q0_q1_by_subject,
    evaluate_q0_q1_probe,
    fit_categorical_model,
    fit_categorical_proper_score_models,
    fit_q0_q1,
    fit_q0_q1_probe,
    fit_token_order,
    fit_train_only_token_order,
    fnirs_marginal,
    fnirs_marginal_from_cooccurrence,
    fnirs_token_marginal,
    log_lift,
    matched_minus_deranged_expected_residual_log_lift,
    matched_minus_deranged_residual_log_lift,
    pair_concentration,
    positive_vs_negative_lag_specificity,
    predict_categorical_proba,
    residual_log_lift,
    residual_log_lift_from_lifts,
    soft_cooccurrence,
    soft_cooccurrence_tensor,
    subject_block_bootstrap,
    summarize_lagged_coupling,
    top_pair_jaccard,
    top_pair_stability,
    top_pairs,
    validate_lags,
    validate_probabilities,
)

__all__ = [
    # Standard patch-feature contract.
    "CANONICAL_SIGNAL_UNIT",
    "DEFAULT_FEATURE_SPEC",
    "FEATURE_SPEC_SCHEMA_VERSION",
    "FeatureDefinition",
    "FeatureExtractionManifest",
    "FrequencyBand",
    "PatchFeatureBatch",
    "PhysiologicalPatchFeatureSpec",
    "extract_eeg_patch_features",
    "extract_fnirs_patch_features",
    "extract_physiological_patch_features",
    # Subject-balanced token physiology.
    "TOKEN_PHYSIOLOGY_SCHEMA_VERSION",
    "TokenPhysiologyConfig",
    "TokenPhysiologyResult",
    "analyze_token_physiology",
    "match_token_signatures",
    # Leakage-safe representation information ledger.
    "InformationLedgerConfig",
    "TOKEN_INFORMATION_LEDGER_SCHEMA_VERSION",
    "build_token_representations",
    "evaluate_information_ledger",
    # End-to-end Atlas orchestration.
    "ATLAS_SCHEMA_VERSION",
    "ModalitySplitAtlas",
    "analyze_export_split",
    "build_token_physiology_atlas",
    "load_token_export",
    "prepare_measurement_feature_caches",
    # Boundary-aware sequence and lag analysis.
    "SEQUENCE_ANALYSIS_SCHEMA",
    "SequenceSummary",
    "analyze_cross_modal_lags",
    "circular_shift_coupling_null",
    "coupling_metrics_from_counts",
    "cross_modal_lag_counts",
    "markov_log_loss",
    "occupancy_counts",
    "summarize_sequences",
    "transition_counts",
    # Historical coupling-identifiability surface.
    "build_lag_pair_table",
    "conditional_probabilities_from_counts",
    "effective_conditional_probabilities",
    "gaussian_conditional_mutual_information",
    "lag_mutual_information",
    "load_export_split",
    "loso_ridge_scores",
    "occupancy_weighted_gauge",
    "patch_features",
    "patch_features_torch",
    "subject_block_bootstrap_gain",
    # Train-only-standardized LC-SPVQ native targets.
    "EEG_NATIVE_FEATURES",
    "FNIRS_COMPONENT_ROLES",
    "FNIRS_NATIVE_FEATURES",
    "MaskedStandardizer",
    "NativeFeatureTargets",
    "apply_masked_standardizer",
    "extract_eeg_native_targets",
    "extract_fnirs_native_targets",
    "fit_masked_standardizer",
    # Held-out soft lagged-token coupling.
    "CategoricalModel",
    "LAGGED_COUPLING_SCHEMA_VERSION",
    "LaggedCategoricalRows",
    "Q0Q1Models",
    "TokenOrder",
    "apply_token_order",
    "build_lagged_categorical_rows",
    "categorical_proper_scores",
    "conditional_fnirs_given_eeg",
    "conditional_log_lift",
    "dirichlet_conditional",
    "dirichlet_smoothed_conditional",
    "evaluate_categorical_model",
    "evaluate_categorical_proper_score_increment",
    "evaluate_q0_q1",
    "evaluate_q0_q1_by_subject",
    "evaluate_q0_q1_probe",
    "fit_categorical_model",
    "fit_categorical_proper_score_models",
    "fit_q0_q1",
    "fit_q0_q1_probe",
    "fit_token_order",
    "fit_train_only_token_order",
    "fnirs_marginal",
    "fnirs_marginal_from_cooccurrence",
    "fnirs_token_marginal",
    "log_lift",
    "matched_minus_deranged_expected_residual_log_lift",
    "matched_minus_deranged_residual_log_lift",
    "pair_concentration",
    "positive_vs_negative_lag_specificity",
    "predict_categorical_proba",
    "residual_log_lift",
    "residual_log_lift_from_lifts",
    "soft_cooccurrence",
    "soft_cooccurrence_tensor",
    "subject_block_bootstrap",
    "summarize_lagged_coupling",
    "top_pair_jaccard",
    "top_pair_stability",
    "top_pairs",
    "validate_lags",
    "validate_probabilities",
]
